name : deploy to kebsas01
on :
  push:
    branches: 
      - master
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: tiyee/action-ssh@release
        with:
          host: ${{ secrets.HOST }} 
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          command: cd /root/repo/xtrabackup/ && git pull origin kebsas01